#!/bin/sh

for test in *.bas
  do
    tname=$(basename $test .bas)
    ../basic < $tname.bas > $tname.s 2> $tname.log
    gcc -g $tname.s ../lib/*.o -o $tname.exe
    echo " ****** $tname ****** "

    # Check compiler output
    diff $tname.s $tname.s.ref

    # Check compiler log messages
    if [ -f $tname.log.ref ]
      then
        diff $tname.log $tname.log.ref
      fi

    # Check program output
    if [ -x $tname.exe -a -f $tname.out.ref ]
      then
        ./$tname.exe > $tname.out
        diff $tname.out $tname.out.ref
      fi 
  done

